/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author idra8
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        escritorio = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        jMenuAdoptante = new javax.swing.JMenu();
        MenuItemAgregarAdoptante = new javax.swing.JMenuItem();
        MenuItemActualizarAdoptante = new javax.swing.JMenuItem();
        MenuItemEliminarAdoptante = new javax.swing.JMenuItem();
        jMenuMascota = new javax.swing.JMenu();
        MenuItemAgregarMascota = new javax.swing.JMenuItem();
        MenuItemActualizarMascota = new javax.swing.JMenuItem();
        MenuItemEliminarMascota = new javax.swing.JMenuItem();
        jMenuFormulario = new javax.swing.JMenu();
        MenuItemAgregarFormularios = new javax.swing.JMenuItem();
        MenuItemActualizarFormulario = new javax.swing.JMenuItem();
        MenuItemEliminarFormulario = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 181, Short.MAX_VALUE)
        );

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ONG de Adopciones VYC");

        jButton1.setText("jButton1");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/e19fcf96-6cbc-483d-b236-1ed05fc0afa1.jpg"))); // NOI18N

        jMenuAdoptante.setText("Adoptante");
        jMenuAdoptante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAdoptanteActionPerformed(evt);
            }
        });

        MenuItemAgregarAdoptante.setText("Agregar Adoptante");
        MenuItemAgregarAdoptante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAgregarAdoptanteActionPerformed(evt);
            }
        });
        jMenuAdoptante.add(MenuItemAgregarAdoptante);

        MenuItemActualizarAdoptante.setText("Actualizar Adoptante");
        MenuItemActualizarAdoptante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemActualizarAdoptanteActionPerformed(evt);
            }
        });
        jMenuAdoptante.add(MenuItemActualizarAdoptante);

        MenuItemEliminarAdoptante.setText("Eliminar Adoptante");
        MenuItemEliminarAdoptante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemEliminarAdoptanteActionPerformed(evt);
            }
        });
        jMenuAdoptante.add(MenuItemEliminarAdoptante);

        menu.add(jMenuAdoptante);

        jMenuMascota.setText("Mascota");
        jMenuMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMascotaActionPerformed(evt);
            }
        });

        MenuItemAgregarMascota.setText("Agregar mascota");
        MenuItemAgregarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAgregarMascotaActionPerformed(evt);
            }
        });
        jMenuMascota.add(MenuItemAgregarMascota);

        MenuItemActualizarMascota.setText("Actualizar Mascota");
        MenuItemActualizarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemActualizarMascotaActionPerformed(evt);
            }
        });
        jMenuMascota.add(MenuItemActualizarMascota);

        MenuItemEliminarMascota.setText("Eliminar Mascota");
        MenuItemEliminarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemEliminarMascotaActionPerformed(evt);
            }
        });
        jMenuMascota.add(MenuItemEliminarMascota);

        menu.add(jMenuMascota);
        jMenuMascota.getAccessibleContext().setAccessibleDescription("");

        jMenuFormulario.setText("Formularios");
        jMenuFormulario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFormularioActionPerformed(evt);
            }
        });

        MenuItemAgregarFormularios.setText("Agregar formulario");
        MenuItemAgregarFormularios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAgregarFormulariosActionPerformed(evt);
            }
        });
        jMenuFormulario.add(MenuItemAgregarFormularios);

        MenuItemActualizarFormulario.setText("Actualizar Formulario");
        MenuItemActualizarFormulario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemActualizarFormularioActionPerformed(evt);
            }
        });
        jMenuFormulario.add(MenuItemActualizarFormulario);

        MenuItemEliminarFormulario.setText("EliminarFormulario");
        MenuItemEliminarFormulario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemEliminarFormularioActionPerformed(evt);
            }
        });
        jMenuFormulario.add(MenuItemEliminarFormulario);

        menu.add(jMenuFormulario);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(751, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 946, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuAdoptanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAdoptanteActionPerformed

       
    }//GEN-LAST:event_jMenuAdoptanteActionPerformed

    private void jMenuMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMascotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuMascotaActionPerformed

    private void jMenuFormularioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFormularioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuFormularioActionPerformed

    private void MenuItemAgregarAdoptanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAgregarAdoptanteActionPerformed
        VentanaAgregarAdoptante ventanaAdoptante = new VentanaAgregarAdoptante();
        ventanaAdoptante.setVisible(true);
    }//GEN-LAST:event_MenuItemAgregarAdoptanteActionPerformed

    private void MenuItemAgregarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAgregarMascotaActionPerformed
        VentanaAgregarMascota ventanaMascota = new VentanaAgregarMascota();
        ventanaMascota.setVisible(true);
    }//GEN-LAST:event_MenuItemAgregarMascotaActionPerformed

    private void MenuItemAgregarFormulariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAgregarFormulariosActionPerformed
        VentanaAgregarFormulario ventanaForm = new VentanaAgregarFormulario();
        ventanaForm.setVisible(true);
    }//GEN-LAST:event_MenuItemAgregarFormulariosActionPerformed

    private void MenuItemActualizarAdoptanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemActualizarAdoptanteActionPerformed
        VentanaActualizarAdoptante ventanaActAdoptante = new VentanaActualizarAdoptante();
        ventanaActAdoptante.setVisible(true);
    }//GEN-LAST:event_MenuItemActualizarAdoptanteActionPerformed

    private void MenuItemEliminarAdoptanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemEliminarAdoptanteActionPerformed
        VentanaEliminarAdoptante ventanaElimAdoptante = new VentanaEliminarAdoptante();
        ventanaElimAdoptante.setVisible(true);
    }//GEN-LAST:event_MenuItemEliminarAdoptanteActionPerformed

    private void MenuItemActualizarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemActualizarMascotaActionPerformed
        VentanaActualizarMascota ventanaActMascota = new VentanaActualizarMascota();
        ventanaActMascota.setVisible(true);
    }//GEN-LAST:event_MenuItemActualizarMascotaActionPerformed

    private void MenuItemEliminarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemEliminarMascotaActionPerformed
        VentanaEliminarMascota ventanaElimMascota = new VentanaEliminarMascota();
        ventanaElimMascota.setVisible(true);
    }//GEN-LAST:event_MenuItemEliminarMascotaActionPerformed

    private void MenuItemActualizarFormularioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemActualizarFormularioActionPerformed
        VentanaActualizarFormulario ventanaActFormulario = new VentanaActualizarFormulario();
        ventanaActFormulario.setVisible(true);
    }//GEN-LAST:event_MenuItemActualizarFormularioActionPerformed

    private void MenuItemEliminarFormularioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemEliminarFormularioActionPerformed
        VentanaEliminarFormulario ventanaElimFormulario = new VentanaEliminarFormulario();
        ventanaElimFormulario.setVisible(true);
    }//GEN-LAST:event_MenuItemEliminarFormularioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItemActualizarAdoptante;
    private javax.swing.JMenuItem MenuItemActualizarFormulario;
    private javax.swing.JMenuItem MenuItemActualizarMascota;
    private javax.swing.JMenuItem MenuItemAgregarAdoptante;
    private javax.swing.JMenuItem MenuItemAgregarFormularios;
    private javax.swing.JMenuItem MenuItemAgregarMascota;
    private javax.swing.JMenuItem MenuItemEliminarAdoptante;
    private javax.swing.JMenuItem MenuItemEliminarFormulario;
    private javax.swing.JMenuItem MenuItemEliminarMascota;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenuAdoptante;
    private javax.swing.JMenu jMenuFormulario;
    private javax.swing.JMenu jMenuMascota;
    private javax.swing.JMenuBar menu;
    // End of variables declaration//GEN-END:variables
}
